version: '3'
services:
    # PHP Service
    app:                                 # Just change this line to csvuploader-app
        container_name: csvUploader-app
        build:
            context: ./docker-compose/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - '2201:22'
        networks:
            - laravel
    # Database Service
    db:
        image: mysql:5.7
        container_name: csvUploader-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: csv-uploader
            MYSQL_ROOT_PASSWORD: password
        networks:
            - laravel
    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: csvUploader-nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - .:/var/www/html
            - ./docker-compose/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker-compose/nginx/certs:/etc/nginx/certs
        depends_on:
            - app
            - db
        networks:
            laravel:
                aliases:
                    - uploader.local
networks:
    laravel:
